baseURL = "https://blog.qiyuex.top" # <head> 里面的 baseurl 信息，填你的博客地址
title = "QiYue's Blog" # 浏览器的标题
languageCode = "zh-cn" # 语言
hasCJKLanguage = true # 开启可以让「字数统计」统计汉字
theme = "LeaveIt" # 主题 (需要自己下载)

paginate = 11 # 每页的文章数
enableEmoji = true # 支持 Emoji
enableRobotsTXT = true # 支持 robots.txt
googleAnalytics = "" # Google 统计 id

preserveTaxonomyNames = true

[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true

[Permalinks]
 posts = "/:year/:filename/"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4

[params]
    since = 2018
    author = "Ray"                          # Author's name
    avatar = "/images/me/avatar.jpg"           # Author's avatar
    subtitle = "Just for Fun"                  # Subtitle
    cdn_url = ""           # Base CDN URL
    home_mode = "" # post or other
    enableGitalk = true # gitalk 评论系统

    google_verification = ""

    description = "" # (Meta) 描述
    keywords = "" # site keywords

    beian = ""
    baiduAnalytics = ""

    license= '本作品采用<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议</a>进行许可。'

[params.social]
    GitHub = "Ray-Keiyaku"
    Wechat = "/images/me/wechat.png"  # Wechat QRcode image
    Email   = "zrztt@outlook.com"
    Telegram = "QiYuex"
    # Twitter = "xxoo"
    # Instagram = "xxoo"
    # Facebook = "xxoo"
    # Dribbble = "xxoo"
    # Medium = "xxoo"

# [params.gitalk] # Github: https://github.com/gitalk/gitalk
#     clientID = "f39a9b9686b70bfb8880" # Your client ID
#     clientSecret = "e19fa0562b68b8b3db776b46178b89295f51a0a8" # Your client secret
#     repo = "ray-keiyaku.github.io" # The repo to store comments
#     owner = "Ray-Keiyaku" # Your GitHub ID
#     admin= "Ray-Keiyaku" # Required. Github repository owner and collaborators. (Users who having write access to this repository)
#     id= "location.pathname" # The unique id of the page.
#     labels= "gitalk" # Github issue labels. If you used to use Gitment, you can change it
#     perPage= 15 # Pagination size, with maximum 100.
#     pagerDirection= "last" # Comment sorting direction, available values are 'last' and 'first'.
#     createIssueManually= false # If it is 'false', it is auto to make a Github issue when the administrators login.
#     distractionFreeMode= false # Enable hot key (cmd|ctrl + enter) submit comment.

[params.valine]
    enable = true
    appId = 'LRdGXLYwaNDfkOsCCytrrA8L-gzGzoHsz'
    appKey = '1mkIUd25e8WzN6xUQU8otIsL'
    notify = false  # mail notifier , https://github.com/xCss/Valine/wiki
    verify = false # Verification code
    avatar = 'mp' 
    placeholder = 'Σ(っ °Д °;)っ你咋不评论就想走啊！'
    visitor = true